name: Development

on:
  push:
    branches: 
      - 'feature/**'

jobs:
  Development-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: skiddph/actions-env@v1.0.2
        with:
          prefix: ""

      - name: Install frontend deps
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy frontend via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:  
          username: 'ubuntu'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './client/build/*'
          remote_path: '/home/ubuntu/test_miever'